added a file explaining where all the relevant odin files are and wha…
clulab/tomcat-text pull request #250
Opened 2022-01-21 19:32 UTC by remo-help

Just a small addition:

added a short docs file that explain where Odin relevant files are located and what they do, this is part of an effort to ensure that our architecture can be quickly understood by newcomers

2022-01-22 18:45 UTC, adarshp requested changes
Thanks! However, I think src/main/resources is too deep a location for these docs. Can you create a new top-level 'docs' directory at the root of the repo and put the file there instead? Also include a suffix in the filename so people can immediately recognize the file type. You can use .txt, or if you think you'll add markdown formatting later, you can use .md.

2022-01-22 18:52 UTC, adarshp commented
Ah, forgot another point - `src/main/resources` is also not the right place for the document, since the `src` directory is meant to contain only things that are required to build or run programs.

2022-01-25 13:11 UTC, remo-help reviewed
changes implemented

2022-01-25 18:01 UTC, adarshp approved these changes

2022-01-28 17:18 UTC, merged