scopt argument parsing
clulab/tomcat-text pull request #306
Opened 2022-06-21 21:10 UTC by jastier

The Dialog Agents now use [scopt ](https://github.com/scopt/scopt) for argument parsing.   This required a slight change in that the optional TA3 version number argument used by the Reprocessor Agent is now preceded by two dashes.   Other than that the usage for all agents has not changed.

2022-06-21 21:21 UTC, kwalcock commented
Cool.  The code looks nice.  What do you think of the library?  Is it worth the time to learn?  Would you want use it again?

2022-06-21 21:23 UTC, kwalcock commented
And do contributors to this project get to play Minecraft?

2022-06-21 21:55 UTC, adarshp requested changes
@jastier - looks good, but could you make a couple of changes:

- Line 28: Could you set a default value for host (`localhost`)
- Line 31: Could you set the default value for port as 1883. Also, should the type be `Int` instead of `String`?
- Line 56: could you change 'Bus' to 'broker'? Mosquitto is an MQTT broker.
- Line 60: Could you change 'Bus' to 'broker', and remove 'name'?

2022-06-21 21:56 UTC, adarshp commented
> And do contributors to this project get to play Minecraft?

@kwalcock - yes, as much Minecraft as their hearts desire :) If you (or anybody you know) is interested in being a pilot participant, here's the info: https://ml4ai.github.io/tomcat/become_a_participant.html

2022-06-21 22:06 UTC, merged

2022-06-21 22:20 UTC, kwalcock commented
It's a long shot, but you might try these student groups:

https://arizona.campusgroups.com/esports/home/
https://arizona.campusgroups.com/club1081/home/ (Video Game Developers Club)

2022-06-21 22:21 UTC, adarshp commented
Thanks @kwalcock !

2022-06-23 23:47 UTC, jastier commented
> Cool. The code looks nice. What do you think of the library? Is it worth the time to learn? Would you want use it again?

scopt has a few quirks,  but these are mostly harmless: 

1. The help page text lists optional arguments before required arguments, even though they are not written in that order in the code.  This is harmless because when I construct each Dialog Agent instance I hard code them in the correct order.  
2. The help page also includes a blank line after each command, then lists the arguments for that command.   It messes up the formatting visually, but again it is harmless.  
3. Each optional argument can have at most one value.   If you want more you can create a map with Python-style kwargs but the no-spaces formatting will test your typing skills.  Or you can do as we did here and just adapt your input for the way scopt does things.  

On the nice side of things:

1. scopt generates its own help pages which is probably its best feature.
2. It seems robust, it did what I expected it to do once I learned what to expect.
3. It was easy to learn.  The examples on the [git repo](https://github.com/scopt/scopt) are really helpful.
4. It provides a consistent interface. 

Overall I like it, and I will use it again.