update need presence rule
clulab/tomcat-text pull request #326
Opened 2022-09-26 02:54 UTC by chencc33

2022-09-28 20:25 UTC, remo-help requested changes
We should make the `NeedPresence` label a subset of the `HelpRequest` label.That seems intuitive to me

2022-10-05 20:56 UTC, remo-help approved these changes

2022-10-05 21:03 UTC, remo-help requested changes
The way the rule is currently set up it will overmatch with "MoveTo" due to the "come" trigger

it also does not correctly extract arguments in "engineer we need you here" without the comma

we need to make some adjustements to allow the arguments to be captured properly

2022-10-13 06:45 UTC, chencc33 commented
I added conditions for 'I need you in A2' and also 'I need Engineer in A2' which will also match the NeedRole label. If you have concerns about it, I will go ahead and revise my rules. @remo-help

2022-10-18 02:03 UTC, remo-help approved these changes

2022-10-18 02:03 UTC, merged